    //http://www.mlb.com/fantasylookup/json/named.fb_team_lineup.bam?period_id=31&team_id=55988
    var myApp = angular.module('myApp', []);
    myApp.controller('teamController', function($scope, $http, $q, $timeout) {
        $scope.lineupJSON = null;
        $scope.Joel = [];
        // $scope.Joel = [{
        //     "elig_bn": "y",
        //     "player_name": "Los Angeles Dodgers",
        //     "elig_dl": "n",
        //     "position": "P",
        //     "team_name": "Los Angeles Dodgers",
        //     "is_locked": "y",
        //     "game_time": "7:10 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "y",
        //     "probable_pitcher_name": "Zack Greinke",
        //     "is_undroppable": "n",
        //     "player_id": "119",
        //     "game_date": "08/22",
        //     "slot": "P",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "n",
        //     "elig_ss": "n",
        //     "team_file_code": "la",
        //     "slot_val": "PS",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "425844",
        //     "league_player_id": "5825812",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Buster Posey",
        //     "elig_dl": "n",
        //     "position": "C/1B/U",
        //     "team_name": "San Francisco Giants",
        //     "is_locked": "y",
        //     "game_time": "4:05 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "y",
        //     "player_id": "457763",
        //     "game_date": "08/22",
        //     "slot": "C",
        //     "elig_1b": "y",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "sf",
        //     "slot_val": "C",
        //     "elig_c": "y",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826529",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Jose Abreu",
        //     "elig_dl": "n",
        //     "position": "1B/U",
        //     "team_name": "Chicago White Sox",
        //     "is_locked": "y",
        //     "game_time": "9:10 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "y",
        //     "player_id": "547989",
        //     "game_date": "08/22",
        //     "slot": "1B",
        //     "elig_1b": "y",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "cws",
        //     "slot_val": "1B",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5825861",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Dee Gordon",
        //     "elig_dl": "n",
        //     "position": "2B/U",
        //     "team_name": "Miami Marlins",
        //     "is_locked": "y",
        //     "game_time": "7:10 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "y",
        //     "player_id": "543829",
        //     "game_date": "08/22",
        //     "slot": "2B",
        //     "elig_1b": "n",
        //     "elig_2b": "y",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "mia",
        //     "slot_val": "2B",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5825846",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Manny Machado",
        //     "elig_dl": "n",
        //     "position": "3B/U",
        //     "team_name": "Baltimore Orioles",
        //     "is_locked": "y",
        //     "game_time": "7:05 PM",
        //     "elig_3b": "y",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "592518",
        //     "game_date": "08/22",
        //     "slot": "3B",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "bal",
        //     "slot_val": "3B",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826257",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Ian Desmond",
        //     "elig_dl": "n",
        //     "position": "SS/U",
        //     "team_name": "Washington Nationals",
        //     "is_locked": "y",
        //     "game_time": "7:05 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "435622",
        //     "game_date": "08/22",
        //     "slot": "SS",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "y",
        //     "team_file_code": "was",
        //     "slot_val": "SS",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826130",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Shin-Soo Choo",
        //     "elig_dl": "n",
        //     "position": "OF/U",
        //     "team_name": "Texas Rangers",
        //     "is_locked": "y",
        //     "game_time": "7:08 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "425783",
        //     "game_date": "08/22",
        //     "slot": "OF",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "tex",
        //     "slot_val": "OF",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826035",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Carlos Gonzalez",
        //     "elig_dl": "n",
        //     "position": "OF/U",
        //     "team_name": "Colorado Rockies",
        //     "is_locked": "y",
        //     "game_time": "8:10 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "471865",
        //     "game_date": "08/22",
        //     "slot": "OF",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "col",
        //     "slot_val": "OF",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826329",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Gregory Polanco",
        //     "elig_dl": "n",
        //     "position": "OF/U",
        //     "team_name": "Pittsburgh Pirates",
        //     "is_locked": "y",
        //     "game_time": "4:05 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "570256",
        //     "game_date": "08/22",
        //     "slot": "OF",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "pit",
        //     "slot_val": "OF",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5825953",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Ryan Zimmerman",
        //     "elig_dl": "n",
        //     "position": "1B/3B/OF/U",
        //     "team_name": "Washington Nationals",
        //     "is_locked": "y",
        //     "game_time": "7:05 PM",
        //     "elig_3b": "y",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "475582",
        //     "game_date": "08/22",
        //     "slot": "U",
        //     "elig_1b": "y",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "was",
        //     "slot_val": "Util",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826445",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Josh Hamilton",
        //     "elig_dl": "y",
        //     "position": "OF/U",
        //     "team_name": "Texas Rangers",
        //     "is_locked": "y",
        //     "game_time": "7:08 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "285078",
        //     "game_date": "08/22",
        //     "slot": "Bn",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "tex",
        //     "slot_val": "Bn",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826348",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Yadier Molina",
        //     "elig_dl": "n",
        //     "position": "C/U",
        //     "team_name": "St. Louis Cardinals",
        //     "is_locked": "y",
        //     "game_time": "8:40 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "425877",
        //     "game_date": "08/22",
        //     "slot": "Bn",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "stl",
        //     "slot_val": "Bn",
        //     "elig_c": "y",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826243",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Hanley Ramirez",
        //     "elig_dl": "n",
        //     "position": "SS/OF/U",
        //     "team_name": "Boston Red Sox",
        //     "is_locked": "y",
        //     "game_time": "7:10 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "y",
        //     "player_id": "434670",
        //     "game_date": "08/22",
        //     "slot": "Bn",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "y",
        //     "team_file_code": "bos",
        //     "slot_val": "Bn",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826446",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Justin Turner",
        //     "elig_dl": "n",
        //     "position": "2B/3B/SS/U",
        //     "team_name": "Los Angeles Dodgers",
        //     "is_locked": "y",
        //     "game_time": "7:10 PM",
        //     "elig_3b": "y",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "457759",
        //     "game_date": "08/22",
        //     "slot": "Bn",
        //     "elig_1b": "n",
        //     "elig_2b": "y",
        //     "elig_util": "y",
        //     "elig_ss": "y",
        //     "team_file_code": "la",
        //     "slot_val": "Bn",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826418",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Joc Pederson",
        //     "elig_dl": "n",
        //     "position": "OF/U",
        //     "team_name": "Los Angeles Dodgers",
        //     "is_locked": "y",
        //     "game_time": "7:10 PM",
        //     "elig_3b": "n",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "592626",
        //     "game_date": "08/22",
        //     "slot": "Bn",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "la",
        //     "slot_val": "Bn",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826211",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "Yasmany Tomas",
        //     "elig_dl": "n",
        //     "position": "3B/OF/U",
        //     "team_name": "Arizona Diamondbacks",
        //     "is_locked": "y",
        //     "game_time": "7:10 PM",
        //     "elig_3b": "y",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "630111",
        //     "game_date": "08/22",
        //     "slot": "Bn",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "ari",
        //     "slot_val": "Bn",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826566",
        //     "elig_of": "y",
        //     "is_pending_trade": "n"
        // }, {
        //     "elig_bn": "y",
        //     "player_name": "David Wright",
        //     "elig_dl": "y",
        //     "position": "3B/U",
        //     "team_name": "New York Mets",
        //     "is_locked": "y",
        //     "game_time": "8:10 PM",
        //     "elig_3b": "y",
        //     "elig_ps": "n",
        //     "probable_pitcher_name": "",
        //     "is_undroppable": "n",
        //     "player_id": "431151",
        //     "game_date": "08/22",
        //     "slot": "DL",
        //     "elig_1b": "n",
        //     "elig_2b": "n",
        //     "elig_util": "y",
        //     "elig_ss": "n",
        //     "team_file_code": "nym",
        //     "slot_val": "DL",
        //     "elig_c": "n",
        //     "probable_pitcher_id": "",
        //     "league_player_id": "5826370",
        //     "elig_of": "n",
        //     "is_pending_trade": "n"
        // }];

        $scope.init = function() {
            $.getJSON('http://anyorigin.com/dev/get?url=http%3A//www.mlb.com/fantasylookup/json/named.fb_team_lineup.bam%3Fteam_id%3D55988%26period_id%3D30&callback=?', function(data) {
                //alert(JSON.sdy(data.contents));
                $scope.Joel = [];
                //alert(JSON.stringify($scope.Joel));
                $scope.lineupJSON = data.contents.fb_team_lineup.queryResults.row;
                angular.forEach($scope.lineupJSON, function(player) {
                    $scope.Joel.push(player);
                });
                console.log(JSON.stringify($scope.lineupJSON));
            });
        };
    });
